### ISSUE TITLE
Unable to fetch...

### ISSUE THREAD

**Issue by ehn** [Sha-Darim/brandriskute#6]
I'm getting a lot of errors in the logs recently:

```
2022-03-10 02:18:00 ERROR (SyncWorker_3) [custom_components.brandriskute.sensor] Unable to fetch current risk from Brandrisk Ute.
2022-03-10 02:18:00 ERROR (SyncWorker_3) [custom_components.brandriskute.sensor] HTTP Error 503: Service Unavailable
2022-03-10 02:18:01 ERROR (SyncWorker_3) [custom_components.brandriskute.sensor] Unable to fetch forecast from Brandrisk Ute.
2022-03-10 02:18:01 ERROR (SyncWorker_3) [custom_components.brandriskute.sensor] HTTP Error 503: Service Unavailable
2022-03-10 02:18:01 ERROR (SyncWorker_3) [custom_components.brandriskute.sensor] Unable to fetch prohibition from Brandrisk Ute.
2022-03-10 02:18:01 ERROR (SyncWorker_3) [custom_components.brandriskute.sensor] HTTP Error 503: Service Unavailable
2022-03-10 02:18:01 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform brandriskute
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
if (icon := (entry and entry.icon) or self.icon) is not None:
File "/config/custom_components/brandriskute/sensor.py", line 85, in icon
if self._api.current['grassIndex'] > self._api.current['woodIndex']:
KeyError: 'grassIndex'
2022-03-10 02:18:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up brandriskute platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
if (icon := (entry and entry.icon) or self.icon) is not None:
File "/config/custom_components/brandriskute/sensor.py", line 85, in icon
if self._api.current['grassIndex'] > self._api.current['woodIndex']:
KeyError: 'grassIndex'
2022-03-10 02:18:01 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform brandriskute
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
if (icon := (entry and entry.icon) or self.icon) is not None:
File "/config/custom_components/brandriskute/sensor.py", line 131, in icon
if self._api.current['grassIndex'] > self._api.current['woodIndex']:
KeyError: 'grassIndex'
```

Is there a problem with the integration or the upstream API?

Running Home Assistant 2022.3.3.

**Comment by ehn** [comment]
Not seeing any more of these errors, so I'm assuming it was an API issue. Unless others are seeing anything similar, I think this can be closed.
